
import React from 'react';
import './ToolsPage.css';

function ToolsPage() {
  return (
    <div className="tools-page">
      <div className="tools-hero">
        <h1>Tools & Credits</h1>
        <p>
          Learn about the technologies and AI models behind GLAMprompt
        </p>
      </div>

      <div className="tools-grid">
        <div className="tool-card tool-card--featured">
          <div className="tool-header">
            <div className="tool-icon-wrap tool-icon--apertus">
              <span className="tool-icon-text">A</span>
            </div>
            <div>
              <h3>Apertus LLM</h3>
              <span className="tool-role">Seed Prompt Generator</span>
            </div>
          </div>
          <p>
            Apertus is the sovereign AI from Switzerland. The seed prompts in the GLAMprompt library
            were generated by Apertus 70B 1.0 running on Public AI.
          </p>
          <div className="tool-specs">
            <div className="spec">
              <span className="spec-label">Role</span>
              <span className="spec-value">Generated 19 seed prompts across 5 categories</span>
            </div>
            <div className="spec">
              <span className="spec-label">Focus</span>
              <span className="spec-value">OpenGLAM, accessibility, preservation, community engagement, education, creative reuse</span>
            </div>
            <div className="spec">
              <span className="spec-label">Utility</span>
              <span className="spec-value"><a href="https://publicai.ch">Public AI Inference</a></span>
            </div>
          </div>
        </div>

        <div className="tool-card tool-card--featured">
          <div className="tool-header">
            <div className="tool-icon-wrap tool-icon--claude">
              <span className="tool-icon-text">C</span>
            </div>
            <div>
              <h3>Claude Opus 4.6 (Anthropic)</h3>
              <span className="tool-role">Application Generator</span>
            </div>
          </div>
          <p>
            This web application was generated by Claude, Anthropic's AI assistant. The entire
            frontend — component architecture, styling, data management, and content layout — was
            produced in a single one-shot generation that cost approximately $2.
          </p>
          <div className="tool-specs">
            <div className="spec">
              <span className="spec-label">Model</span>
              <span className="spec-value">Claude (Anthropic)</span>
            </div>
            <div className="spec">
              <span className="spec-label">Task</span>
              <span className="spec-value">Full-stack React SPA generation from markdown sources</span>
            </div>
            <div className="spec">
              <span className="spec-label">Parameters</span>
              <span className="spec-value">Reasoning effort: 99 (near-maximum)</span>
            </div>
            <div className="spec">
              <span className="spec-label">Approach</span>
              <span className="spec-value">Component-based architecture, CSS modules, persistent storage, responsive design</span>
            </div>
            <div className="spec">
              <span className="spec-label">Platform</span>
              <span className="spec-value"><a href="https://openrouter.ai">OpenRouter</a></span>
            </div>
          </div>
        </div>

        <div className="tool-card">
          <div className="tool-header">
            <div className="tool-icon-wrap tool-icon--react">
              <span className="tool-icon-text">⚛</span>
            </div>
            <div>
              <h3>React 18</h3>
              <span className="tool-role">Frontend Framework</span>
            </div>
          </div>
          <p>
            The user interface is built with React 18, using functional components, hooks for state management,
            and a component-based architecture for maintainability.
          </p>
          <div className="tool-specs">
            <div className="spec">
              <span className="spec-label">Version</span>
              <span className="spec-value">React 18.2.0</span>
            </div>
            <div className="spec">
              <span className="spec-label">Rendering</span>
              <span className="spec-value">Client-side SPA with createRoot</span>
            </div>
            <div className="spec">
              <span className="spec-label">Modules</span>
              <span className="spec-value">ES Modules via importmap (esm.sh CDN)</span>
            </div>
          </div>
        </div>

        <div className="tool-card">
          <div className="tool-header">
            <div className="tool-icon-wrap tool-icon--ts">
              <span className="tool-icon-text">TS</span>
            </div>
            <div>
              <h3>TypeScript</h3>
              <span className="tool-role">Type Safety</span>
            </div>
          </div>
          <p>
            All components are written in TypeScript (.tsx), providing type safety for prompts, categories,
            navigation state, and form handling.
          </p>
          <div className="tool-specs">
            <div className="spec">
              <span className="spec-label">Typing</span>
              <span className="spec-value">Prompt, Category, Page interfaces</span>
            </div>
            <div className="spec">
              <span className="spec-label">Benefit</span>
              <span className="spec-value">Compile-time error detection, better developer experience</span>
            </div>
          </div>
        </div>

        <div className="tool-card">
          <div className="tool-header">
            <div className="tool-icon-wrap tool-icon--css">
              <span className="tool-icon-text">◎</span>
            </div>
            <div>
              <h3>CSS (Vanilla)</h3>
              <span className="tool-role">Styling</span>
            </div>
          </div>
          <p>
            Styling uses co-located vanilla CSS files with modern techniques: CSS Grid, Flexbox, custom properties,
            gradients, and responsive media queries. No CSS framework or preprocessor is used.
          </p>
          <div className="tool-specs">
            <div className="spec">
              <span className="spec-label">Pattern</span>
              <span className="spec-value">Component-scoped CSS files</span>
            </div>
            <div className="spec">
              <span className="spec-label">Responsive</span>
              <span className="spec-value">Mobile-first with breakpoints at 768px</span>
            </div>
          </div>
        </div>

        <div className="tool-card">
          <div className="tool-header">
            <div className="tool-icon-wrap tool-icon--storage">
              <span className="tool-icon-text">💾</span>
            </div>
            <div>
              <h3>Persistent Storage</h3>
              <span className="tool-role">Data Persistence</span>
            </div>
          </div>
          <p>
            Community-contributed prompts are persisted using the Zustand API —
            an async key-value store that survives page reloads.
          </p>
          <div className="tool-specs">
            <div className="spec">
              <span className="spec-label">API</span>
              <span className="spec-value">Zustand library</span>
            </div>
            <div className="spec">
              <span className="spec-label">Data Format</span>
              <span className="spec-value">JSON-serialized prompt array</span>
            </div>
          </div>
        </div>
      </div>

      <section className="architecture-section">
        <h2>Architecture Overview</h2>
        <div className="arch-diagram">
          <div className="arch-layer arch-layer--source">
            <div className="arch-layer-label">Source</div>
            <div className="arch-items">
              <div className="arch-item">Apertus LLM<br /><small>Seed Prompts (.md)</small></div>
              <div className="arch-arrow">→</div>
              <div className="arch-item">Claude<br /><small>App Generation</small></div>
              <div className="arch-arrow">→</div>
              <div className="arch-item">GitHub Pages<br /><small>Deployment</small></div>
            </div>
          </div>
          <div className="arch-connector">▼</div>
          <div className="arch-layer arch-layer--app">
            <div className="arch-layer-label">Application</div>
            <div className="arch-items">
              <div className="arch-item">React SPA</div>
              <div className="arch-item">TypeScript</div>
              <div className="arch-item">CSS Modules</div>
            </div>
          </div>
          <div className="arch-connector">▼</div>
          <div className="arch-layer arch-layer--data">
            <div className="arch-layer-label">Data</div>
            <div className="arch-items">
              <div className="arch-item">Seed Data<br /><small>19 prompts</small></div>
              <div className="arch-item">User Contributions<br /><small>Persistent Storage</small></div>
            </div>
          </div>
          <div className="arch-connector">▼</div>
          <div className="arch-layer arch-layer--pages">
            <div className="arch-layer-label">Pages</div>
            <div className="arch-items">
              <div className="arch-item">Library</div>
              <div className="arch-item">Contribute</div>
              <div className="arch-item">Innovation Lab</div>
              <div className="arch-item">Tools</div>
            </div>
          </div>
        </div>
      </section>

      <section className="open-section">
        <div className="open-card">
          <h3>Built on Open Principles</h3>
          <p>
            GLAMprompt embodies the OpenGLAM ethos: open content, open tools, and community participation.
            The seed prompts, workshop format, and application itself are designed to be shared, remixed,
            and adapted by cultural institutions worldwide.
          </p>
          <div id="repo-container">
            <p>
              <b>loleg / glamprompts</b>
              <br />Apache-2.0 license
            </p>
            <p>Source code: <a href="https://github.com/loleg/glamprompts">GitHub</a></p>
          </div>
          <div className="open-badges">
            <span className="open-badge">Open Source Tools</span>
            <span className="open-badge">Community-Driven</span>
            <span className="open-badge">Accessible Design</span>
            <span className="open-badge">Sovereign AI</span>
          </div>
        </div>
      </section>
    </div>
  );
}

export default ToolsPage;
