
import React from 'react';
import './Footer.css';

function Footer() {
  return (
    <footer className="footer">
      <div className="footer-inner">
        <p className="footer-text">
          <span className="footer-logo">◆ GLAM<span style={{ color: '#6c63ff' }}>prompt</span></span>
          {' '}— An open prompt library for OpenGLAM digital literacy
        </p>
        <p className="footer-sub">
          Seed prompts generated by Apertus LLM · Built with React · Open for contributions
        </p>
      </div>
    </footer>
  );
}

export default Footer;
